#cache:
#  key: "$CI_BUILD_REF_NAME codereach.ca:alpine"
stages:
  - build
  - deploy
build:
  stage: build
  image: docker:latest
  only:
    - "master"
  services:
    - docker:dind
    #  - docker version
    - "docker info"
  script:
    - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - "docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}/nginx:latest --pull ."
    - "docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}/php:latest --pull -f ./php/Dockerfile ."
    - "docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/nginx:latest"
    - "docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/php:latest"
  after_script:
    - "docker logout ${CI_REGISTRY}"
deploy:
  stage: deploy
  image: gitlab/dind:latest
  only:
    - "master"
  environment: production
  services:
    - docker:dind
  before_script:
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOYMENT_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - ssh dockerdeploy@$DEPLOYMENT_SERVER_IP "mkdir ~/php"
    - scp -r ./docker-compose.${CI_PROJECT_NAME}.yml dockerdeploy@${DEPLOYMENT_SERVER_IP}:~/docker-compose.${CI_PROJECT_NAME}.yml
    #    - ssh dockerdeploy@$DEPLOYMENT_SERVER_IP "mkdir ~/php"
    - scp ./php/Dockerfile dockerdeploy@${DEPLOYMENT_SERVER_IP}:~/php/
    - ssh dockerdeploy@$DEPLOYMENT_SERVER_IP "export SG_API_KEY=${SG_API_KEY}; export CI_REGISTRY=${CI_REGISTRY}; export CI_PROJECT_PATH=${CI_PROJECT_PATH}; docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}; docker-compose -f docker-compose.${CI_PROJECT_NAME}.yml stop; docker-compose -f docker-compose.${CI_PROJECT_NAME}.yml rm codereach_nginx; docker-compose -f docker-compose.${CI_PROJECT_NAME}.yml rm codereach_php; docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH}/nginx:latest; docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH}/php:latest; SENDGRID_API_KEY=${SG_API_KEY} docker-compose -f docker-compose.${CI_PROJECT_NAME}.yml up -d"
