version: "3"
networks:
  web:
    external: true
  internal:
    external: false
services:
  web:
    image: nginx:latest
    ports:
      - "9001:80"
    volumes:
      - ./webroot:/webroot
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    labels:
      - "traefik.docker.network: traefik"
      - "traefik.frontend.rule=Host:codereach.ca"
    networks:
      - web
  php:
    image: php:7-fpm
    volumes:
      - ./webroot:/webroot
