version: "3"
services:
  #  proxy:
  #    image: traefik:latest
  #    command: --web --docker --docker.domain=codereach.local --logLevel=DEBUG
  #    networks:
  #      - traefik
  #    ports:
  #      - 80:80
  #      - 443:443
  #      - 8080:8080
  #    volumes:
  #      - /var/run/docker.sock:/var/run/docker.sock
  #      - /etc/traefik/traefik.toml:/traefik.toml
  web:
    image: nginx:latest
    ports:
      - "9001:80"
    volumes:
      - ./webroot:/webroot
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    labels:
      - "traefik.docker.network: traefik"
      - "traefik.frontend.rule=Host:codereach.ca"
    networks:
      - traefik
  php:
    image: php:7-fpm
    volumes:
      - ./webroot:/webroot
    networks:
      - traefik
networks:
  traefik:
    external: true
